### ISSUE TITLE
Need an unique code formatter

### ISSUE THREAD

**Issue by GrapeBaBa** [0xFableOrg/simple-op-stack-rollup#28]
Currently, when I reformat in IDE(pycharm/vscode), some non related code format changed. It is better to specific a formatter. @ayazabbas Could you give us a suggestion which pythonic?

**Comment by ayazabbas** [comment]
From @norswap initial setup of the project I believe we are already using [ruff](https://github.com/astral-sh/ruff) for linting and it looks like it includes a formatter

**Comment by GrapeBaBa** [comment]
> From @norswap initial setup of the project I believe we are already using [ruff](https://github.com/astral-sh/ruff) for linting and it looks like it includes a formatter

however it seems not have a CLI for formatting? `ruff check` not auto format code if I don't use a IDE plugin, both codes passed.

**Comment by ayazabbas** [comment]
Aha, looks like they are working on it https://github.com/astral-sh/ruff/issues/1904

In that case I suggest we use black and isort for formatting

**Comment by norswap** [comment]
I'm really not a fan of strongly opinionated formatters like Black with no opt-outs. But there doesn't really seem to be another good option, is there?

**Comment by ayazabbas** [comment]
autopep8 is less opinionated, maybe we can give that a try

**Comment by norswap** [comment]
Yeah, that seems nice!
