### ISSUE TITLE
Build "bare metal" deploy primitives

### ISSUE THREAD

**Issue by norswap** [0xFableOrg/simple-op-stack-rollup#3]
Our planned architecture calls for a `confgen` component generating a configuration file, piping into `provisioner` component that provisions the infrastructure, piping into a `deployer` component that deploys the rollup.

The most basic configuration of this eschews the provisioner and simply runs the bare shell command to deploy the rollup on the local machine.

The goal is to encapsulate these shell commands in python scripts / functions that cna be then be reused in all the more advanced deployer version (e.g. dockerscripts can call the python scripts). This lets us avoid repeating the same commands, parameter, etc... in multiple places.

As a first step, given that the `confgen` component does not exist yet, we should simply aim for a straightforward script that deploys a rollup. This will help us understand the flow of commands, configuration files, and other moving parts.

Note that interestingly, the Optimism repo doesn't suppor this bare metal option, the only user-facing interface uses docker-compose.

**Comment by GrapeBaBa** [comment]
Which should we implement in MVP, bare metal or docker-compose?

**Comment by norswap** [comment]
Bare metal, then we simply call the python script from the Docker config files.

**Comment by GrapeBaBa** [comment]
> Bare metal, then we simply call the python script from the Docker config files.

OK, for start it, I think we can transform https://github.com/ethereum-optimism/optimism/blob/develop/bedrock-devnet/devnet/__init__.py to some shell scripts first. Is it right direction?

**Comment by norswap** [comment]
Yes, that's exactly the idea!

**Comment by upnodedev** [comment]
> > Bare metal, then we simply call the python script from the Docker config files.
> 
> OK, for start it, I think we can transform https://github.com/ethereum-optimism/optimism/blob/develop/bedrock-devnet/devnet/__init__.py to some shell scripts first. Is it right direction?

Be careful with the latest version of above script. It has a critical bug occurred to anyone in the Optimism discord.

<img width="718" alt="image" src="https://github.com/0xFableOrg/simple-op-stack-rollup/assets/117493285/643f4528-4895-44cc-86b6-547e8944ecb3">

Current confirmed solution to this bug is using

```
git reset 7168db67c5b421975fef2a090aa6e6ee4e3ff298 --hard
```

To rollback to the latest working version

**Comment by norswap** [comment]
Yes, that's exacly the right direction, I'm looking at this rn.

Probably we're going to copy parts of the script over to our own repo (since the one in OP repo are tangled up with using Docker), so we might still be able to use that version if the problems only affect the devnet setup.

But thanks for the warning, that will for sure save us some time trying to figure out an issue that cannot be solved! 🫡

**Comment by norswap** [comment]
Okay, now that we have L1 done, we need to do the same thing for the other components:

- op-geth (aka `l2` in the optimism config, cf. #6)
- op-node
- op-batcher
- op-proposer

The source of truth for the commit we're using is [here](https://github.com/ethereum-optimism/optimism/blob/d3380c89a02799ec86acadf25c9a4a7cedbe49a5/ops-bedrock/docker-compose.yml). It's a bit of a mess, because the command used for various things is specified in many different ways: as an explicit entrypoint file in `docker-compose.yml`, as an implicit entrypoint file (for `entrypoint-batcher.sh`) and as a `CMD` command in a Dockerfile (for `op-proposer/Dockerfile`).

For convenience, the people from Upnode have extracted the various commands [here](https://github.com/upnodedev/op-stack-basic-deployment/tree/main/entrypoints), which is a bit easier to reference.

All of those should probably follow the same pattern as L1 node for the moment: spin them with `processes.PROCESS_MGR.start`. We are already building most of what we need via `roll.py setup`, however for op-geth we need to clone and build that repository, for which we can use the same type of code we use to clone and build the optimism repository.

At this point, I'm pretty used to all that, so I suggest in the interest of speed, I take on spinning the op-node, op-batcher and op-proposer, while I let @GrapeBaBa finish the work on the L1 node. I'll probably take a bit less load later for the docker / cloud work. Targetting completion for Sunday 27 at the latest, but will push things as I do them (but probably starting only on the 23rd unless I can miraculously get some work in before).

In terms of dependencies, the execution engine (op-geth) should be spun first, then all the rest can be started. Interestingly, op-batcher has an explicit logic waiting for the execution engine to be up [in the entrypoint](https://github.com/ethereum-optimism/optimism/blob/d3380c89a02799ec86acadf25c9a4a7cedbe49a5/ops-bedrock/op-batcher-entrypoint.sh) whereas both the proposer and the op-node don't (meaning it's probably handled in-process?)
